#!/usr/bin/env node
// db:migrate — apply the migration set to the LINKED Supabase project.
// Phase 2 U15. A thin wrapper around `supabase db push`, and the wrapper exists
// for exactly one reason: the bare command fails uselessly.
//
// Measured before this file was written:
//
//     $ npm run db:migrate
//     sh: supabase: command not found
//     EXIT=127
//
// That tells an operator nothing about what to install, that the project must
// be linked first, or that `supabase/config.toml` is generated rather than
// checked in (see the deployed-schema record §0 for why it is absent). §8.3 —
// a non-functional affordance must be visibly disabled or LABELLED; an
// affordance that fails obscurely is a trust defect, not a neutral stub.
//
// THIS SCRIPT DOES NOT REPLACE THE CLI OR SIMULATE IT. It checks two
// preconditions, explains either failure, and otherwise hands over to the real
// `supabase db push` — passing its arguments through and, above all, EXITING
// WITH ITS STATUS. A wrapper that swallowed a failed push would report a
// migration as deployed when it was not, which is worse than the obscure error
// it replaced (mutation M4's lesson, at a second site).
import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { join } from "node:path";

const REPO_ROOT = join(import.meta.dirname, "..");
const RECORD = "docs/05-qa/2026-08-12-deployed-schema-record.md";

const cliPresent = spawnSync("supabase", ["--version"], { stdio: "ignore" }).status === 0;

if (!cliPresent) {
  console.error(
    "db:migrate — THE SUPABASE CLI IS NOT INSTALLED (or is not on PATH).\n\n" +
      "This command applies `supabase/migrations/*.sql` to the linked Supabase\n" +
      "project. It is an OPERATOR command: it talks to a real database, and it\n" +
      "is never run in CI.\n\n" +
      "To set it up:\n" +
      "  1. Install the CLI       https://supabase.com/docs/guides/cli\n" +
      "  2. Link the project      supabase link --project-ref <PROJECT_REF>\n" +
      "  3. Re-run                npm run db:migrate\n\n" +
      "`supabase/config.toml` is NOT checked into this repository, and that is\n" +
      "deliberate: it is generated by `supabase init` / `supabase link` against a\n" +
      "version-specific CLI schema, and hand-authoring one that nothing available\n" +
      "could validate is what §2.2 rule 8 forbids. Step 2 produces the real file.\n\n" +
      `Full reasoning, and the deploy-order rules that apply once this works:\n  ${RECORD} §0 and §4\n\n` +
      "NOTE: `npm run verify:migrations` does NOT need any of this. It applies the\n" +
      "same migration set to a throwaway local Postgres and needs no CLI, no\n" +
      "credentials, and no linked project — use it to check the SET is coherent\n" +
      "before you deploy it anywhere.",
  );
  process.exit(1);
}

if (!existsSync(join(REPO_ROOT, "supabase", "config.toml"))) {
  console.error(
    "db:migrate — THE SUPABASE CLI IS INSTALLED, BUT THIS PROJECT IS NOT LINKED.\n\n" +
      "`supabase/config.toml` does not exist. It is generated, not checked in\n" +
      `(${RECORD} §0).\n\n` +
      "  supabase link --project-ref <PROJECT_REF>\n\n" +
      "Then re-run `npm run db:migrate`. Commit the generated config.toml only if\n" +
      "you can verify it against the CLI version that produced it — the reason it\n" +
      "is absent is that nobody could.",
  );
  process.exit(1);
}

// Hand over. `stdio: "inherit"` so the CLI's own prompts and diff output reach
// the operator unmediated, and the exit status is propagated verbatim: this
// wrapper must never turn a failed push into a success.
const push = spawnSync("supabase", ["db", "push", ...process.argv.slice(2)], {
  cwd: REPO_ROOT,
  stdio: "inherit",
});

if (push.error) {
  console.error(`db:migrate — could not run the Supabase CLI: ${push.error.message}`);
  process.exit(1);
}
process.exit(push.status ?? 1);
